spring:
  application:
    name: admin-server
  security:
    user:
      name: root
      password: fanminghui
  boot:
    admin:
      discovery:
        ignored-services: ${spring.application.name}
server:
  port: 9301
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:fanminghui@localhost:7001/eureka