server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://eureka7001.com:7001/eureka/
spring:
  application:
    name: eureka-security-server
  security:
    user:
      name: root
      password: fanminghui