server:
  port: 80
spring:
  application:
    name: consumer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:fanminghui@localhost:7001/eureka
service-url:
  provide-service: http://provider/pay/
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'